// Generated by https://quicktype.io

export interface IUser {
  success: boolean;
  message: string;
  user: User;
}

export interface User {
  token?: string;
  firstname: string;
  lastname: string;
  email: string;
  role: string;
}
